networks:
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 40000000000
        cmd_settings:
            port: 8545
            gas_limit: 6721975
            accounts: 50
compiler:
  solc:
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
